// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type GameState struct {
	SessionID  string
	Game       string
	Difficulty string
	FsmState   string
	Board      string
	Score      int64
	StartedAt  time.Time
}

type Leaderboard struct {
	ID         int64
	Name       string
	Game       string
	Difficulty string
	Score      int64
	PlayedAt   time.Time
}

type Session struct {
	ID          string
	Name        string
	WizardState string
	ChosenGame  string
	ChosenDiff  string
	CreatedAt   time.Time
}
