// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const deleteGameState = `-- name: DeleteGameState :exec
DELETE FROM game_states WHERE session_id = ?
`

func (q *Queries) DeleteGameState(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteGameState, sessionID)
	return err
}

const getGameState = `-- name: GetGameState :one
SELECT session_id, game, difficulty, fsm_state, board, score, started_at FROM game_states WHERE session_id = ?
`

func (q *Queries) GetGameState(ctx context.Context, sessionID string) (GameState, error) {
	row := q.db.QueryRowContext(ctx, getGameState, sessionID)
	var i GameState
	err := row.Scan(
		&i.SessionID,
		&i.Game,
		&i.Difficulty,
		&i.FsmState,
		&i.Board,
		&i.Score,
		&i.StartedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, name, wizard_state, chosen_game, chosen_diff, created_at FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WizardState,
		&i.ChosenGame,
		&i.ChosenDiff,
		&i.CreatedAt,
	)
	return i, err
}

const insertLeaderboardEntry = `-- name: InsertLeaderboardEntry :one
INSERT INTO leaderboard (name, game, difficulty, score) VALUES (?, ?, ?, ?)
RETURNING id, name, game, difficulty, score, played_at
`

type InsertLeaderboardEntryParams struct {
	Name       string
	Game       string
	Difficulty string
	Score      int64
}

func (q *Queries) InsertLeaderboardEntry(ctx context.Context, arg InsertLeaderboardEntryParams) (Leaderboard, error) {
	row := q.db.QueryRowContext(ctx, insertLeaderboardEntry,
		arg.Name,
		arg.Game,
		arg.Difficulty,
		arg.Score,
	)
	var i Leaderboard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Game,
		&i.Difficulty,
		&i.Score,
		&i.PlayedAt,
	)
	return i, err
}

const listLeaderboard = `-- name: ListLeaderboard :many
SELECT id, name, game, difficulty, score, played_at FROM leaderboard
WHERE game = ? AND difficulty = ?
ORDER BY score DESC, played_at ASC
LIMIT 20
`

type ListLeaderboardParams struct {
	Game       string
	Difficulty string
}

func (q *Queries) ListLeaderboard(ctx context.Context, arg ListLeaderboardParams) ([]Leaderboard, error) {
	rows, err := q.db.QueryContext(ctx, listLeaderboard, arg.Game, arg.Difficulty)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Leaderboard{}
	for rows.Next() {
		var i Leaderboard
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Game,
			&i.Difficulty,
			&i.Score,
			&i.PlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGameState = `-- name: UpdateGameState :execrows
UPDATE game_states
SET fsm_state = ?1,
    board     = ?2,
    score     = ?3
WHERE session_id = ?4
  AND fsm_state  = ?5
`

type UpdateGameStateParams struct {
	NewState      string
	Board         string
	Score         int64
	SessionID     string
	ExpectedState string
}

func (q *Queries) UpdateGameState(ctx context.Context, arg UpdateGameStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateGameState,
		arg.NewState,
		arg.Board,
		arg.Score,
		arg.SessionID,
		arg.ExpectedState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSessionName = `-- name: UpdateSessionName :execrows
UPDATE sessions SET name = ?1 WHERE id = ?2
`

type UpdateSessionNameParams struct {
	Name string
	ID   string
}

func (q *Queries) UpdateSessionName(ctx context.Context, arg UpdateSessionNameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSessionName, arg.Name, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSessionWizardState = `-- name: UpdateSessionWizardState :execrows
UPDATE sessions
SET wizard_state = ?1,
    chosen_game  = ?2,
    chosen_diff  = ?3
WHERE id = ?4 AND wizard_state = ?5
`

type UpdateSessionWizardStateParams struct {
	NewState      string
	ChosenGame    string
	ChosenDiff    string
	ID            string
	ExpectedState string
}

func (q *Queries) UpdateSessionWizardState(ctx context.Context, arg UpdateSessionWizardStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSessionWizardState,
		arg.NewState,
		arg.ChosenGame,
		arg.ChosenDiff,
		arg.ID,
		arg.ExpectedState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertGameState = `-- name: UpsertGameState :exec
INSERT INTO game_states (session_id, game, difficulty, fsm_state, board, score)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(session_id) DO UPDATE
  SET game = excluded.game,
      difficulty = excluded.difficulty,
      fsm_state = excluded.fsm_state,
      board = excluded.board,
      score = excluded.score,
      started_at = CURRENT_TIMESTAMP
`

type UpsertGameStateParams struct {
	SessionID  string
	Game       string
	Difficulty string
	FsmState   string
	Board      string
	Score      int64
}

func (q *Queries) UpsertGameState(ctx context.Context, arg UpsertGameStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertGameState,
		arg.SessionID,
		arg.Game,
		arg.Difficulty,
		arg.FsmState,
		arg.Board,
		arg.Score,
	)
	return err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (id) VALUES (?) ON CONFLICT(id) DO NOTHING
`

func (q *Queries) UpsertSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, upsertSession, id)
	return err
}
